version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=your_redis_password
      - HASH_SECRET=your_secret_key_for_hash_verification
      - DEBUG=True
    volumes:
      - ./app:/app/app
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass your_redis_password
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: